version: '2'
services:
   tomcatconfig:
      build:
          context: .
          dockerfile: Dockerfile.TomcatConfig
      container_name: jaj-ops-tomcat-config
      restart: always
   tomcat:
      build:
          context: .
          dockerfile: Dockerfile.TomCat
      container_name: jaj-ops-tomcat
      volumes_from: 
        - tomcatconfig
      ports: 
        - "8081:8080"
      restart: always
   jenkins:
      build:
        context: .
        dockerfile: Dockerfile.Jenkins
      container_name: jaj-ops-jenkins
      environment:
        JAVA_OPTS: "-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"
      ports:
        - "50000:50000"
        - "8080:8080"
      links:
        - tomcat:jaj-ops-tomcat
      volumes_from:
        - jenkinsdata
        - jenkinsplugins
      restart: always
   jenkinsdata:
      build:
          context: .
          dockerfile: Dockerfile.JenkinsDataVolume
      container_name: jaj-ops-jenkins-data-volume
      restart: always
   jenkinsplugins:
      build:
          context: .
          dockerfile: Dockerfile.JenkinsPlugins
      container_name: jaj-ops-jenkins-plugins
      restart: always
   jenkinsswarm:
    image: csanchez/jenkins-swarm-slave
    command: -executors 4
    links:
      - jenkins:jenkins
    environment:
      - "JENKINS_PORT_8080_TCP_ADDR=jenkins"
      - "JENKINS_PORT_8080_TCP_PORT=8080"
