FROM ubuntu

ENV JENKINS_PLUGINS_HOME /var/jenkins_home/plugins
ENV JENKINS_HOME /var/jenkins_home

ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000


RUN groupadd -g ${gid} ${group} \
    && useradd -d "$JENKINS_HOME" -u ${uid} -g ${gid} -m -s /bin/bash ${user}

COPY plugins ${JENKINS_PLUGINS_HOME} 
RUN chown -R ${user}:${group} ${JENKINS_PLUGINS_HOME}

VOLUME ${JENKINS_PLUGINS_HOME} 
CMD sleep infinity
