FROM ubuntu
ENV JENKINS_HOME /var/jenkins_home

ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000

RUN groupadd -g ${gid} ${group} \
    && useradd -d "$JENKINS_HOME" -u ${uid} -g ${gid} -m -s /bin/bash ${user}

COPY resources/jenkins/jenkins_home ${JENKINS_HOME}
RUN chown -R ${user} "$JENKINS_HOME"
VOLUME ${JENKINS_HOME} 
CMD sleep infinity
