FROM sbeliakou/centos:6.7
MAINTAINER Aliaksandr Karavai (aliaksandr_karavai@epam.com)
RUN yum install -y wget tar java-1.7.0 && \
wget http://ftp.byfly.by/pub/apache.org/tomcat/tomcat-7/v7.0.72/bin/apache-tomcat-7.0.72.tar.gz && \
tar -xvf apache-tomcat-7.0.72.tar.gz && \
rm -f apache-tomcat*.tar.gz && \
mv apache-tomcat* /opt/tomcat/ && \
yum erase -y wget tar && \
yum clean all && \
chmod +x /opt/tomcat/bin/*sh
ENTRYPOINT [ "/opt/tomcat/bin/catalina.sh" ]
CMD [ "run" ]
